site_name: Creating Projects with Impact
site_description: 'Designing and building projects with impact'
site_author: 'Dana Abdel Khalek'


nav:
  - Home: index.md
  - Course:
      - Syllabus: course/syllabus.md
  - Chapters:
      - 1. Social Enterprise Basics: chapters/01-social-enterprise-basics.md
      - 2. Design Thinking: chapters/02-design-thinking.md
      - 3. Business Model: chapters/03-business-model.md
  - Glossary: glossary/index.md