site_name: Mkdocs for Intelligent Textbooks
site_description: 'Using the mkdocs build to to create and managed intelligent textbooks. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/mkdocs-for-intelligent-textbooks/'
repo_url: 'https://github.com/dmccreary/mkdocs-for-intelligent-textbooks'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About: about.md
  - Tutorial:
    - Introduction: tutorial/index.md
    - Getting Started: tutorial/getting-started.md
    - Navigation: tutorial/navigation.md
    - Admonitions: tutorial/admonitions.md
    - Quizzes: tutorial/quizzes.md
    - Upper Alpha Lists: tutorial/upper-alpha-lists.md
    - Google Analytics: tutorial/google-analytics.md
  - Prompts:
    - Introduction: prompts/index.md
    - Feature Mapping: prompts/feature-mapping.md
    - Enumerate Concepts: prompts/enumerate-concepts.md
    - Generate Logo: prompts/generate-logo.md

  - Checklist: checklist.md
  - Code Highlight Test: code-highlight-test.md
  - Glossary: glossary.md
  - Table of Contents: toc.md
  - License: license.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down

theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo.png
  favicon: img/favicon.ico
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - md_in_html # required for multiple-choce question numbering
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
extra:
  analytics:
    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-D7X1XT7Z19